### ISSUE TITLE
Easy API for accessing Nested Object Properties in a JsObject

### ISSUE THREAD

**Issue by codeviking** [allenai/common#105]
It'd be great if we extended the `get` API to support queries for deeply nested properties.  I could see both nested object property support like so:

``` scala
 json.get[JsObject]("prop.anotherProp")
```

And also the ability to select items at a specific index of a JsArray, like so:

``` scala
 json.get[String]("prop.anotherProp.someOtherProp[3]")
```

**Comment by jkinkead** [comment]
Sounds like maybe you want HOCON? ;)

**Comment by codeviking** [comment]
I suppose you're right.  

Given we already include typesafe config in (most) of our projects, I just have to figure out how to de-serialize from json into a typesafe config object, right?

**Comment by jkinkead** [comment]
HOCON will parse all valid JSON, and you can serialize any Config object as valid JSON as well.

Really you just need a `JsValue` -> `Config` function (which should be pretty easy to do).

**Comment by codeviking** [comment]
Nice -- well then we're set! Thx.

**Comment by jkinkead** [comment]
Given that we're deprecating `spray-json`, this should be closed.
