### ISSUE TITLE
Semaphore broken on latest common release

### ISSUE THREAD

**Issue by cristipp** [allenai/common#125]
[error](*:update) sbt.ResolveException: unresolved dependency: org.allenai.common#common-core_2.11;1.0.1: not found

https://semaphoreci.com/allenai/euclid/branches/pull-request-10/builds/1

**Comment by schmmd** [comment]
I'm guessing you are missing a resolver in your project.  I think it's working for you on your laptop because you have the dependency cached in your ivy cache.  I'm not sure what you expect me to do.

**Comment by cristipp** [comment]
Thanks for the pointer!

As the "boss" of the project, I'd expect that you'd be responsible for making it work, including in Semaphore. If we need to add a resolver to new projects, it would be nice to have this requirement documented on https://github.com/allenai/common.

**Comment by cristipp** [comment]
Specifically, I pulled Aria's ml library from Sonatype/Nexus with no problems. But common v1.0.1 doesn't work the same way. This needs fixing :)

**Comment by schmmd** [comment]
Please do some basic troubleshooting first, communicate what you've done, and explain your problem and its urgency in English next time.  The amount of detail you added and then your response that I'm responsible to "make it work" in your project makes me feel that this isn't my problem.  Anyone who declares a dependency in their project has the responsibility to know where it's coming from.

 I troubleshooted this by first noting that common 1.0.1 is not on Maven Central http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.allenai.common%22%20AND%20a%3A%22common-core_2.11%22.  It's also not in our internal Nexus repository (http://utility.allenai.org:8081/nexus/#nexus-search;quick~common-core).

This is now a [default resolver](https://github.com/allenai/sbt-plugins/blob/master/src/main/scala/org/allenai/plugins/CoreRepositories.scala#L24), but your [plugins are out of date](https://github.com/allenai/euclid/blob/master/project/plugins.sbt#L1).  You can add the resolver directly.

We had a plan to move our projects from Maven Central to BinTray.  I was working on this but I dropped it to focus on S2.  Presently common is the only dependency that is published to BinTray.  I'm hoping that Hye will tackle organizing our build artifacts.

**Comment by cristipp** [comment]
Thanks for the pointers and for the fast response. Hopefully this sorts out
the issue.

Here are a few more thoughts:

* [Obscure diff situation] I have jars that we publish that work on
Semaphore, so common was somehow "special". Feels natural to ask the
"common" maintainer what's going on. I literally had no idea what else to
try.

* [Big team, we need dedicated maintainers to help the team overall] I
picked the person ostensible responsible for common. That happens to be
you, but it is not personal. Feel free to delegate to someone else.

* [Use better names in code, use code reviews to improve naming]
Resolver.jcenterRepo is a particularly uninformative name. I did poke at
https://github.com/allenai/scholar/blob/master/project/Dependencies.scala
to see what's different, but nothing jumped to my eyes.
"Resolver.allenaiBintrayRepo" would have potentially made my explorations

* [Communication in a large team requires more effort] There is very little
context on the work that has been done around publishing jars and
resolvers. We've been doing Nexus with some degree of success, but there is
where my knowledge ends.

* [Changes that impact other projects should be advertised] It is
definitely unobvious what work goes on the plugins repo and what
implications it has. It would be _very_ nice if updates and implications
were published to dev mailing list. Case in point, a search for
"2015.06.05-0" in my inbox brings nothing.

* [Work should be completed, and committed once it's complete] The fact
that Bintray work has been abandoned midway is not very helpful either. An
more incremental approach, where the update happens within a day (or it
doesn't happen at all) would have prevented most of this.

Thanks again for the timely help,
Cristian

**Comment by schmmd** [comment]
> * [Big team, we need dedicated maintainers to help the team overall] I
picked the person ostensible responsible for common. That happens to be
you, but it is not personal. Feel free to delegate to someone else.

I'm happy to help, but I could use a bit more context at the start next time.

> Resolver.jcenterRepo

The name comes from a plugin we use: https://github.com/softprops/bintray-sbt. `allenaiJcenterRepo` would be misleading, as that would actually be a different resolver for only allenai jars `Resolver.bintrayRepo("allenai", "maven")`.  JCenter is a public area where jars can be published similar to Maven Central. https://bintray.com/bintray/jcenter

> * [Changes that impact other projects should be advertised] It is
definitely unobvious what work goes on the plugins repo and what
implications it has. It would be _very_ nice if updates and implications
were published to dev mailing list. Case in point, a search for
"2015.06.05-0" in my inbox brings nothing.

That's a good suggestion!  I will follow up with Mark and Jesse, who generally publish our plugin updates.

> * [Communication in a large team requires more effort] There is very little
context on the work that has been done around publishing jars and
resolvers. We've been doing Nexus with some degree of success, but there is
where my knowledge ends.

Publishing jars at AI2 is a mess.  Apologies for the low communication on the switch--I somewhat abruptly dropped the project of moving all of our projects to publish via CI to BinTray.  I'm hoping Hye (or someone else) will help us sort this out soon as it's getting unbearable.

**Comment by jkinkead** [comment]
Seems resolved.
