### ISSUE TITLE
bintray publishing is broken since 1.0.5

### ISSUE THREAD

**Issue by cristipp** [allenai/common#135]
File from 1.0.4:  common-core_2.11-1.0.4-javadoc.jar 
File from 1.0.5 (broken): org.allenai.common:common-core_2.11_2.11-1.0.5-javadoc.jar 
File from 1.0.9 (broken): org.allenai.common:common-core_2.11_2.11-1.0.9-javadoc.jar

**Comment by cristipp** [comment]
@jkinkead @schmmd @hiramhye

**Comment by cristipp** [comment]
jcenter view: https://jcenter.bintray.com/org/allenai/common/common-core_2.11/

**Comment by cristipp** [comment]
possibly this PR broke it: https://github.com/allenai/common/pull/129/files

**Comment by schmmd** [comment]
Thanks for noting this @cristipp . @jkinkead, any idea how we didn't notice this until 1.0.9?

**Comment by schmmd** [comment]
It was also possibly broken by a new release of Shippable.  I found some problems in < 1 minute with the new site.

**Comment by jkinkead** [comment]
Yeah, looks like #129 broke the package name while fixing the bintray name.

I'll see what I can do to fix.

**Comment by jkinkead** [comment]
Sigh, we're back to pre- #129 days - it's publishing what looks like the correct binaries, but putting them in the wrong package.

I'll wait to fix until we update the bintray publishing plugin.
