### ISSUE TITLE
Version injector repo url doesn't resolve if a remote url doesn't end it `.git`.

### ISSUE THREAD

**Issue by codeviking** [allenai/common#145]
https://github.com/allenai/common/blob/master/core/src/main/scala/org/allenai/common/Version.scala#L43

It's valid to configure a remote url without an ending `.git`, i.e.:

```
git@github.com:allenai/scholar
```

The `Version` plugin fails to handle this, as it requires the url to end with a `.git`.

**Comment by bbstilson** [comment]
Some way, somehow, I will destroy this plugin.

For now, I'm gonna close this as a "will not fix".
