### ISSUE TITLE
Migrating from bintray resolver for a public project

### ISSUE THREAD

**Issue by chrisc36** [allenai/common#234]
I have an old public project (https://github.com/allenai/pdffigures2) the depends on common.

It used to have a jfrog bintray resolver that would allow it to include common as a dependency, that service is not longer available breaking the build.

I understand I should be able to fix this by using the newer sbt-codeartifact plugin, but I can't figure out exactly how to go about doing that. I have tried adding the plugin and setting:

codeArtifactUrl := "https://org-allenai-s2-896129387501.d.codeartifact.us-west-2.amazonaws.com/maven/private"

But I am getting software.amazon.awssdk.services.codeartifact.model.AccessDeniedException:User is not authorized to perform: codeartifact:GetAuthorizationToken on resource: arn:aws:codeartifact:us-west-2:896129387501:domain/org-allenai-s2 because no resource-based policy allows the codeartifact:GetAuthorizationToken action

Am I missing something? Is there a way to fix pdffigures? I have gotten several external people requesting we fix the repo so it seems like it is still in use.

**Comment by schmmd** [comment]
I'm pretty unfamiliar with this stuff now, but I think the way forward would be to remove your dependency on `common` and then to figure out how to get things to work again.

I have looked into similar problems on older projects, and found other things broken in old versions of SBT.  I would be happy to pair with you on this, but my ability to help might be limited.

**Comment by chrisc36** [comment]
It looks like removing the dependency is pretty easy to do, so I will just do that.
