### ISSUE TITLE
character encoding problem with LineCollectionIo in pipeline

### ISSUE THREAD

**Issue by afader** [allenai/common#51]
I'm doing some basic serialization stuff with the pipeline code. `LineCollectionIo` seems to choke on unicode. 

Here's a test that shows the problem (may be possible to simplify this, just copied from other tests):  https://github.com/afader/common/blob/master/pipeline/src/test/scala/org/allenai/pipeline/TestArtifactIO.scala#L66-L75

Is there a way to pass an implicit `scala.io.Codec` in my test case?

**Comment by rodneykinney** [comment]
This was fixed in #86
