### ISSUE TITLE
(core) Enum is not deserializable due to being an abstract class

### ISSUE THREAD

**Issue by markschaake** [allenai/common#91]
Noticed this when trying to use [`Enum`](https://github.com/allenai/common/blob/master/core/src/main/scala/org/allenai/common/Enum.scala) in a distributed application (S2 Crawler). When attempting to deserialize an Enum via default Java deserialization you'll get a runtime error that is due to Enum being an abstract class that requires a constructor. To solve this, we should make `Enum` a trait instead of an abstract class.

**Comment by jkinkead** [comment]
Fixed in `v1.0.19`.
